spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_HOST}:${PGSQL_PORT:5432}/gmdb
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    liquibase-schema: liquibase
    default-schema: gmdb
